<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Anshumans-MacBook-Pro.local" failures="4" tests="6" name="HubSpot Functional Regression Test -- FF" time="45.782" errors="0" timestamp="2020-03-16T07:36:44 EDT">
  <testcase classname="com.qa.hubspot.tests.LoginPageTest" name="verifyLoginPageTitleTest" time="4.628"/>
  <testcase classname="com.qa.hubspot.tests.LoginPageTest" name="verifyLoginPageTitleTest" time="8.43"/>
  <testcase classname="com.qa.hubspot.tests.LoginPageTest" name="verifySignUpLinkTest" time="0.071">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at com.qa.hubspot.tests.LoginPageTest.verifySignUpLinkTest(LoginPageTest.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- verifySignUpLinkTest -->
  <testcase classname="com.qa.hubspot.tests.LoginPageTest" name="verifySignUpLinkTest" time="0.026">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at com.qa.hubspot.tests.LoginPageTest.verifySignUpLinkTest(LoginPageTest.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- verifySignUpLinkTest -->
  <testcase classname="com.qa.hubspot.tests.LoginPageTest" name="loginTest" time="14.517">
    <failure type="java.lang.AssertionError" message="did not expect to find [Anshuman Sehgal] but found [null]">
      <![CDATA[java.lang.AssertionError: did not expect to find [Anshuman Sehgal] but found [null]
at com.qa.hubspot.tests.LoginPageTest.loginTest(LoginPageTest.java:80)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.qa.hubspot.tests.LoginPageTest" name="loginTest" time="13.03">
    <failure type="java.lang.AssertionError" message="did not expect to find [Anshuman Sehgal] but found [null]">
      <![CDATA[java.lang.AssertionError: did not expect to find [Anshuman Sehgal] but found [null]
at com.qa.hubspot.tests.LoginPageTest.loginTest(LoginPageTest.java:80)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.qa.hubspot.tests.LoginPageTest" name="loginTest_WrongCredentials" time="0.0">
    <ignored/>
  </testcase> <!-- loginTest_WrongCredentials -->
</testsuite> <!-- HubSpot Functional Regression Test - FF -->
